# Navegador a usar
webdriver.driver=msedge

# Ruta de tu EdgeDriver
msedge.driver=C:\workplace\drivers\msedgedriver.exe

# Directorio donde se generarán los reportes
serenity.outputDirectory=target/serenity-reports

# Timeout por defecto para WebDriver (en segundos)
webdriver.timeouts.implicitlywait=5

# Tamaño de ventana al iniciar (puedes cambiar a maximize)
webdriver.startup.maximized=true

# Idioma de la UI (opcional)
serenity.browser.locale=en

